# Generated by Django 2.2.17 on 2021-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_doner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(default='blood', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='supply',
            field=models.IntegerField(default=300000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
