# Generated by Django 2.2.17 on 2021-01-15 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_resource_danger_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='danger_supply',
        ),
        migrations.AddField(
            model_name='doner',
            name='last_notified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
