# Generated by Django 2.2.17 on 2021-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_auto_20210114_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='birth_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
