# Generated by Django 2.2.17 on 2021-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_auto_20210114_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='phone_number',
            field=models.CharField(default='12982470869', max_length=11),
            preserve_default=False,
        ),
    ]
