# Generated by Django 2.2.17 on 2021-01-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_auto_20210114_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='danger_supply',
            field=models.IntegerField(default=30000),
        ),
    ]
